### ISSUE TITLE
一般雨课堂也可以使用本脚本

### ISSUE THREAD

**Issue by CamberLoid** [ShevonKuan/yuektang_ppt2pdf#1]
描述中仅说了长江雨课堂可以使用
经测试 www.yuketang.cn/web/print 也可应用此脚本
因为不想pr请在描述和user.js里添加如上URI

感谢, 写的很不错, Star了

**Comment by ShevonKuan** [comment]
感谢提醒，因为我们学校目前用的最多的是长江～，我也没有其他雨课堂的课程来进行测试，所以考虑不周，请见谅。
另外，如果雨课堂可以使用的话，说明其前端架构一致，如果可以的话，希望帮忙验证更多的雨课堂是否可用，我也会考虑通配符http://*.yuketang.cn/web/print。

**Comment by CamberLoid** [comment]
~~但咱们只用原版雨课堂pwp~~

---

会留意来自其他学校的使用情况（包括荷花等）。
Closing the issue
