### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by hui-shao** [ShevonKuan/yuektang_ppt2pdf#4]
requirements.txt 中，
`Flask==1.1.2`
应修改为
`Flask>=2.1.0`
否则会出现错误：
`ImportError: cannot import name 'escape' from 'jinja2'`

---

很不错很好用的工具，大赞一个，
Js + Flask 的想法也很新颖，自己最近学了点 Js 也想这么搞爬虫
结果找到了作者这个 Repo，学习了学习了

**Comment by ShevonKuan** [comment]
谢谢您的支持，我的Flash运行环境确实是`1.1.2`且并未出现您所说的错误，请问可以发一下`log`和错误定位嘛。
> 其实现在我觉得用node会比较好，后端nodejs前端脚本js嵌入，不过考虑到node本地环境比较复杂并且编译出二进制比较麻烦，所以考虑用python，也是我考试周抱佛脚的最佳选择哈哈哈。

**Comment by hui-shao** [comment]
> 谢谢您的支持，我的Flash运行环境确实是`1.1.2`且并未出现您所说的错误，请问可以发一下`log`和错误定位嘛。
> > 其实现在我觉得用node会比较好，后端nodejs前端脚本js嵌入，不过考虑到node本地环境比较复杂并且编译出二进制比较麻烦，所以考虑用python，也是我考试周抱佛脚的最佳选择哈哈哈。

啊哈 其实也没什么额外的log。人在外边不太方便发 /捂脸
就是运行py文件时，会立刻跳出我上述的异常，然后脚本退出。
我想这个可能和 python版本有关系，我疏忽了，没有说明。
我的是 python 3.9 
(10) ，是按照网上的方法更新 Flask 后解决了。
